spring:
  redis:
    host: localhost
    port: 6379
    database: 0 #???0????
    jedis:
      pool:
        max-active: 8 #?????
        max-idle: 4 #??????
        max-wait: 1ms #????????
        min-idle: 0 #??????